"use client";

import { useRef } from "react";
import type { PhotoItem } from "./PhotoUploader";

export function DraggablePhoto({ photo, index, fit, selected, onSelect, onPosition, onResize }: { photo: PhotoItem; index: number; fit: "cover" | "contain"; selected: boolean; onSelect: (id: string) => void; onPosition: (id: string, x: number, y: number) => void; onResize: (id: string, frameWidth: number, frameHeight: number) => void }) {
  const start = useRef({ clientX: 0, clientY: 0, x: 0, y: 0, stageWidth: 1, stageHeight: 1, minX: 0, maxX: 0, minY: 0, maxY: 0 });
  const dragging = useRef(false);
  const resizeStart = useRef({ active: false, x: 0, y: 0, width: 100, height: 100, pixelWidth: 1, pixelHeight: 1, axis: "both" as "width" | "height" | "both" });
  const clamp = (value: number, min: number, max: number) => Math.max(min, Math.min(max, value));
  const movementBounds = (element: HTMLElement) => { const stage = element.parentElement!.getBoundingClientRect(); const frame = element.getBoundingClientRect(); return { stage, minX: photo.moveX + ((stage.left - frame.left) / stage.width) * 100, maxX: photo.moveX + ((stage.right - frame.right) / stage.width) * 100, minY: photo.moveY + ((stage.top - frame.top) / stage.height) * 100, maxY: photo.moveY + ((stage.bottom - frame.bottom) / stage.height) * 100 }; };
  const clampSize = (value: number) => Math.max(55, Math.min(180, value));
  const beginResize = (event: React.PointerEvent<HTMLButtonElement>, axis: "width" | "height" | "both") => { event.preventDefault(); event.stopPropagation(); const rect = event.currentTarget.parentElement!.getBoundingClientRect(); resizeStart.current = { active: true, x: event.clientX, y: event.clientY, width: photo.frameWidth, height: photo.frameHeight, pixelWidth: rect.width, pixelHeight: rect.height, axis }; event.currentTarget.setPointerCapture(event.pointerId); };
  const continueResize = (event: React.PointerEvent<HTMLButtonElement>) => { event.stopPropagation(); const start = resizeStart.current; if (!start.active) return; const width = start.axis === "height" ? start.width : clampSize(start.width + ((event.clientX - start.x) / start.pixelWidth) * start.width); const height = start.axis === "width" ? start.height : clampSize(start.height + ((event.clientY - start.y) / start.pixelHeight) * start.height); onResize(photo.id, width, height); };
  return <figure className={`photo-cell cell-${index + 1} shape-${photo.shape} ${selected ? "selected-photo" : ""}`} tabIndex={0} aria-label={`Foto ${index + 1}. Arrastrá o usá las flechas para moverla libremente sobre la hoja.`}
    onPointerDown={(event) => { onSelect(photo.id); dragging.current = true; const bounds = movementBounds(event.currentTarget); start.current = { clientX: event.clientX, clientY: event.clientY, x: photo.moveX, y: photo.moveY, stageWidth: bounds.stage.width, stageHeight: bounds.stage.height, minX: bounds.minX, maxX: bounds.maxX, minY: bounds.minY, maxY: bounds.maxY }; event.currentTarget.setPointerCapture(event.pointerId); }}
    onPointerMove={(event) => { if (!dragging.current) return; const s = start.current; onPosition(photo.id, clamp(s.x + ((event.clientX - s.clientX) / s.stageWidth) * 100, s.minX, s.maxX), clamp(s.y + ((event.clientY - s.clientY) / s.stageHeight) * 100, s.minY, s.maxY)); }}
    onPointerUp={() => { dragging.current = false; }} onPointerCancel={() => { dragging.current = false; }}
    onKeyDown={(event) => { const d = event.shiftKey ? 5 : 1; const b = movementBounds(event.currentTarget); if (event.key === "ArrowLeft") onPosition(photo.id, clamp(photo.moveX - d, b.minX, b.maxX), photo.moveY); if (event.key === "ArrowRight") onPosition(photo.id, clamp(photo.moveX + d, b.minX, b.maxX), photo.moveY); if (event.key === "ArrowUp") onPosition(photo.id, photo.moveX, clamp(photo.moveY - d, b.minY, b.maxY)); if (event.key === "ArrowDown") onPosition(photo.id, photo.moveX, clamp(photo.moveY + d, b.minY, b.maxY)); }}
    data-photo-id={photo.id} style={{ width: `${photo.frameWidth}%`, height: `${photo.frameHeight}%`, left: `${photo.moveX}%`, top: `${photo.moveY}%` }}>
    <img draggable={false} src={photo.url} alt={photo.name} style={{ objectFit: fit, objectPosition: `${photo.x}% ${photo.y}%`, transform: `scale(${photo.zoom})` }} />
    <span className="drag-hint">ARRASTRÁ PARA MOVER</span>
    {selected && <><button className="resize-handle resize-right" aria-label="Ajustar ancho" onPointerDown={(event) => beginResize(event, "width")} onPointerMove={continueResize} onPointerUp={() => { resizeStart.current.active = false; }} /><button className="resize-handle resize-bottom" aria-label="Ajustar alto" onPointerDown={(event) => beginResize(event, "height")} onPointerMove={continueResize} onPointerUp={() => { resizeStart.current.active = false; }} /><button className="resize-handle resize-corner" aria-label="Ajustar ancho y alto" onPointerDown={(event) => beginResize(event, "both")} onPointerMove={continueResize} onPointerUp={() => { resizeStart.current.active = false; }} /></>}
  </figure>;
}
